version: "3"
services:
  ui:
    env_file:
      - ./ui/.env
    build:
      context: ./ui/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ui-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "10001:8080"
  server:
    env_file:
      - ./server/.env
    build:
      context: ./server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - server-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "10002:3000"
volumes:
  ui-extensions:
  server-extensions:
