version: "3"
services:
  ui:
    build:
      context: ./ui/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ui-node-modules:/workspace/ui/node_modules
      - ui-extensions:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
  server:
    build:
      context: ./server/.devcontainer
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    entrypoint: "npm start"
    ports:
      - "8080:8080"
volumes:
  ui-node-modules:
  ui-extensions:
