version: "3"
services:
  ui:
    env_file:
      - ./ui/.env
    build:
      context: ./ui/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ui-node-modules:/workspace/ui/node_modules
      - ui-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "10001:8080"
  server:
    env_file:
      - ./server/.env
    build:
      context: ./server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - server-node-modules:/workspace/server/node_modules
      - server-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "10002:3000"
volumes:
  ui-node-modules:
  server-node-modules:
  ui-extensions:
  server-extensions:
